### ISSUE TITLE
使用RotationAnimation 两端不一致情况

### ISSUE THREAD

**Issue by xwc520** [doric-pub/Doric#209]
rotation(setpIndex: number) {
        let chevron = this.getChevronBySetp(setpIndex)
        let rotation = new RotationAnimation()
        rotation.duration = 0
        rotation.fromRotation = 0
        rotation.toRotation = -0.5
        rotation.fillMode = FillMode.Forward
        this.getView().doAnimation(context, rotation)
    }

这段代码第二次执行的时候，android上view没有再次旋转，在ios上又旋转了一次。实际情况我不想让他再旋转一次，我把duration设置为0.0000001来解决这个问题。

**Comment by penfeizhou** [comment]
这个问题已经修复，请升级到最新的SDK。
