### ISSUE TITLE
关于如何开启调试模式？

### ISSUE THREAD

**Issue by ogli324** [doric-pub/Doric#271]
你好， 新年快乐！
不知道js代码是否可以在浏览器远程调试， 我查阅了文档没找到类似于webView.setWebContentsDebuggingEnabled(true);这样的开关设置。
谢谢~

**Comment by penfeizhou** [comment]
可以调试.需要通过doric-cli命令行工具和Visual Studio Code进行.
具体的步骤我们后面会在文档里详细说明.

**Comment by penfeizhou** [comment]
> 可以调试.需要通过doric-cli命令行工具和Visual Studio Code进行.
> 具体的步骤我们后面会在文档里详细说明.

https://doric.pub/docs/devkit.html
