### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by sshhsun-code** [doric-pub/Doric#438]
你好，最近在了解Doric框架，想知道 在绘制效率方面，想对比RN，我们的优化主要是哪些方向。

**Comment by penfeizhou** [comment]
Doric的与RN都是用于跨端开发的框架,虽然整体上看都是用JS开发(Doric中是TypeScript),不过核心思路是不同的.
如果只看绘制效率方面,Doric是具有优势的,从这几个方面可以解释一下为什么:
1. Doric在JS API层的设计尽量贴合原生,从JS到原生组件的映射,相较于RN框架更简单直接,节省了转义开销
2. 跨端框架性能瓶颈是JS和Native间的调用和数据传输开销,在Doric中数据会批量传输,JS和Native间的调用频次可以优化到尽量少.
3. Doric中页面布局数据是通过脏值检测的机制传回到Native的,所以如果是局部更新,只需要回传少量的脏值数据.
从这几方面看,可以从原理上解释为什么Doric的绘制效率会优于RN.

**Comment by penfeizhou** [comment]
## 欢迎加入Doric社区讨论交流
| 钉钉 | 微信 |
| ---- | ---- |
| !<img src="https://user-images.githubusercontent.com/9526211/141051788-c9df135b-bc88-4850-a2c8-b0a65f78fd57.png" height="500px"/> | <img src="https://user-images.githubusercontent.com/9526211/141051914-2f9e34c7-a4fc-446a-8d17-693cadee0d5b.png" height="500px"/>|
