### ISSUE TITLE
可以断点调试js吗？

### ISSUE THREAD

**Issue by yinyinnie** [doric-pub/Doric#469]
请教一个问题，在Android里面，如何在js里面进行断点调试，有类似chrome dev tool那样的调试功能吗？

**Comment by jingpeng** [comment]
可以的，依赖devkit即可，有一个调试面板

**Comment by penfeizhou** [comment]
https://doric.pub/docs/devkit.html#%E6%96%AD%E7%82%B9%E8%B0%83%E8%AF%95

**Comment by yinyinnie** [comment]
我详细描述下场景：比如我们用Android WebView加载一个网页时，使用chrome dev tool能直接看到运行在WebView中的网页以及js，然后可以断点调试，doric可以有类似的功能吗？

**Comment by penfeizhou** [comment]
可以看一下文档，是可以断点调试的

**Comment by penfeizhou** [comment]
> 可以看一下文档，是可以断点调试的

https://doric.pub/docs/devkit.html#%E6%96%AD%E7%82%B9%E8%B0%83%E8%AF%95

**Comment by yinyinnie** [comment]
谢谢解答，文档之前已经看过了，我再仔细研究下文档。
