### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by stephenRen-ai** [doric-pub/Doric#650]
[
![image](https://github.com/doric-pub/Doric/assets/22440662/8a489780-5cfd-4e4d-9012-8864acd4d046)
](url)

when run 'onTearDown' fucntion, plugin hold context, context want to clear plugin, so can not clear

**Comment by jingpeng** [comment]
Java's GC considers objects "garbage" if they aren't reachable through a chain starting at a garbage collection root, so these objects will be collected. Even though objects may point to each other to form a cycle, they're still garbage if they're cut off from the root.

See the section on unreachable objects in Appendix A: The Truth About Garbage Collection in [Java Platform Performance: Strategies and Tactics](http://techbus.safaribooksonline.com/book/programming/java/0201709694) for the gory details.

**Comment by stephenRen-ai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
